name: Update SwiftKey APK

# زمان‌بندی هر هفته - در این مثال هر یکشنبه ساعت 00:00 (به وقت UTC)
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:  # این امکان رویداد اجرایی دستی نیز فراهم می‌کند

jobs:
  update-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download APK
      run: |
        echo "Downloading APK from Farsroid..."
        # لینک مستقیم فایل APK مربوط به مود v8a:
        APK_URL="https://www.dl.farsroid.com/ap/SwiftKey-Keyboard-9.10.23.20-Mod-Arm64-v8a(FarsRoid.Com).apk"
        curl -L -o swiftkey.apk "$APK_URL"

    - name: Commit changes if APK updated
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        # اگر فایل swiftkey.apk تغییر کرده باشد؛ سپس commit انجام می‌شود
        git add swiftkey.apk
        if ! git diff --cached --quiet; then
          git commit -m "Automatically updated SwiftKey APK"
          git push
        else
          echo "No changes in APK file. Skipping commit."
        fi
